services:
  server:
    build:
      context: .
    volumes:
       - ../kutt.sqlite:/var/lib/kutt/kutt.sqlite
       - custom:/kutt/custom
    environment:
      DB_FILENAME: "/var/lib/kutt/kutt.sqlite"
      JWT_SECRET: verylongscared1283971@87213897askdjghaskjd
    ports:
      - 3333:3000
volumes:
  custom: